### ISSUE TITLE
Failed to exexute script...

### ISSUE THREAD

**Issue by HyunJae5463** [developers192/DetailedLoLRPC#12]
Getting this Error when launching the exe. I suppose its because the program expects League to be installed on C Drive, which is not the case for me.

```
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "disabler.py", line 9, in disableNativePresence
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Riot Games\\League of Legends\\Plugins\\plugin-manifest.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DetailedLoLRPC.py", line 18, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 120, in spawn_main
  File "multiprocessing\spawn.py", line 133, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by developers192** [comment]
Yeah, it searches for the Riot Client and expects League to be in the same "Riot Games" folder as the Riot Client. 
To fix this, you can try to manually reset the preferences:

1. Press Windows + R, type in `%appdata%`, then delete the entire DetailedLoLRPC folder.
2. Manually open League through Riot Client.
3. Open DLRPC, when it prompts you that it might not work properly if opened after League, press Yes.
4. Close League, then start the game through DetailedLoLRPC.

If this still doesn't work, I'll probably have to implement manual path selection.

**Comment by developers192** [comment]
Please let me know if it worked or not xd
