### ISSUE TITLE
Background Task does not close after closing the client

### ISSUE THREAD

**Issue by xaiyadev** [developers192/DetailedLoLRPC#23]
I dont know if this a feature, but if I close the client and after 1-2 Hours open it again (what happens a bit often) I get an error message.
Most of the time I ignore it but recently I started noticing that these mini tasks of this RPC are kept open.

Not a big deal, the RPC still works, but it still is a bit annoying...

**Comment by developers192** [comment]
When it happens again, can you screenshot the error message? Thanks

**Comment by xaiyadev** [comment]
```
Failed to execute script: 'DetailedLoLRPC' due to unhandled exception: 'NoneType' object has no attribute 'write'

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "disabler.py", line 19, in disableNativePresence
PermissionError: [Errno 13] Permission denied: 'D:\\Riot Games\\League of Legends\\Plugins\\plugin-manifest.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DetailedLoLRPC.py", line 19, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by developers192** [comment]
Probably fixed in the latest update. Lmk if the problem persists.
